<?php
/**
 * @file
 * Ticker_Tape  - Ticker Tape to scroll text horizontally with pure CSS
 */

 /**
 * Implements hook_autoload_info.
 */
function ticker_tape_autoload_info() {
  return array(
    'ticker_tape_horizontal_plugin_style' => 'styles/ticker_tape_horizontal_plugin_style.inc',
    'CarlosRios\PHP_CSS' => 'includes/class-php-css.php'
  );
}

/**
 * Implements hook_views_api().
 */
function ticker_tape_views_api() {
  $module_path = backdrop_get_path('module', 'ticker_tape');
  return array(
    'api' => '3.0',
    'path' => $module_path . '/views',
    //'template path' => $module_path,
  );
}

/**
 * Implements hook_theme().
 */
function ticker_tape_theme() {
  return array(
    'ticker-tape-horizontal-plugin-style' => array(
      'variables' => array('items' => NULL, 'options' => NULL, 'identifier' => NULL),
    ),
  );
}
